on:
  push:
    branches:
      - main 
      - github-action
  pull_request:
    branches:
      - main
      - github-action
jobs:
  my-job:
    runs-on: self-hosted
    name: job1 - Hello world action step
    steps:
      - name: Step1 - Hello world action step
        id: hello
        uses: omenking/barsoom@0.0.6
        with:
          name: 'yog'
      # Use the output from the `hello` step
      - name: Get the Output

        run: echo "The time was ${{ steps.hello.outputs.greeting }}"


